spring:
  application.name: registration-service-ramunajam
  profiles.active: default
---
spring:
  profiles: default
  main.show-banner: false
  pidfile: ${java.io.tmpdir}/registration-service-ramunajam.pid
  activemq:
    broker-url : vm://localhost?broker.persistent=true&broker.useJmx=true&broker.persistent=true&broker.useShutdownHook=true&jms.redeliveryPolicy.maximumRedeliveries=3&jms.redeliveryPolicy.redeliveryDelay=2000
    in-memory: false
    pooled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-password
    default-encoding: UTF-8
server:
  port: 8080
logging:
  file: ${java.io.tmpdir}/registration-service-ramunajam.log
  config: classpath:logback.xml
management:
  port: 8081
  context-path: /management
endpoints:
  autoconfig.enabled: false
  beans.enabled: false
  configprops.enabled: false
  dump.enabled: true
  env.enabled: false
  health.enabled: true
  info.enabled: false
  mappings.enabled: false
  metrics.enabled: true
  shutdown.enabled: true
  trace.enabled: true
---